import React from "react";
import { createPortal } from "react-dom";
import { X, Printer } from "lucide-react";
import { HourEntry, StaffMember, GeneralConfig } from "../types";

interface TimesheetProps {
  staff: StaffMember;
  entries: HourEntry[]; // already filtered to this staff + period
  periodLabel: string;
  config: GeneralConfig;
  lang: "en" | "fr";
  onClose: () => void;
}

const TYPE_LABEL: Record<string, { fr: string; en: string }> = {
  worked: { fr: "Travaillé", en: "Worked" },
  absent: { fr: "Absent", en: "Absent" },
  sick: { fr: "Maladie", en: "Sick" },
  holiday: { fr: "Congé", en: "Holiday" },
};

export default function Timesheet({ staff, entries, periodLabel, config, lang, onClose }: TimesheetProps) {
  const approved = entries.filter(e => e.status === "approved").sort((a, b) => a.date.localeCompare(b.date));
  const totalHours = approved.filter(e => e.type === "worked").reduce((s, e) => s + e.hours, 0);
  const absenceDays = approved.filter(e => e.type !== "worked").length;

  const generatedAt = new Date().toLocaleString(lang === "fr" ? "fr-FR" : "en-US", {
    day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit",
  });

  return createPortal(
    <div className="print-portal-root fixed inset-0 bg-slate-950/80 z-50 flex flex-col items-center justify-center gap-4 p-4 overflow-y-auto">
      <div className="print:hidden flex gap-2">
        <button
          className="px-4 py-2 bg-lime-400 text-slate-950 font-bold rounded-xl hover:bg-lime-300 transition-all flex items-center gap-2 text-sm"
          onClick={() => window.print()}
        >
          <Printer size={16} /> {lang === "fr" ? "Imprimer" : "Print"}
        </button>
        <button
          className="px-4 py-2 bg-slate-900 border border-slate-800 text-slate-300 rounded-xl text-sm"
          onClick={onClose}
        >
          <X size={16} className="inline mr-1" /> {lang === "fr" ? "Fermer" : "Close"}
        </button>
      </div>

      <div id="timesheet-print-area" className="bg-white text-slate-900 rounded-2xl p-8 w-full max-w-2xl shadow-2xl text-sm">
        <div className="flex justify-between items-start border-b border-slate-300 pb-4 mb-4">
          <div>
            <h1 className="text-lg font-extrabold">{config.resto_name || "—"}</h1>
            <p className="text-xs text-slate-500 mt-0.5">
              {lang === "fr" ? "Relevé d'heures / Timesheet" : "Timesheet"}
            </p>
          </div>
          <div className="text-right text-xs text-slate-500">
            <p>{lang === "fr" ? "Généré le" : "Generated on"} {generatedAt}</p>
            <p className="italic">{lang === "fr" ? "Document généré par Brigado" : "Document generated by Brigado"}</p>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4 mb-5 text-xs">
          <div>
            <span className="text-slate-500 uppercase font-bold tracking-wider text-[10px]">{lang === "fr" ? "Employé" : "Employee"}</span>
            <p className="font-semibold text-sm">{staff.name}</p>
          </div>
          <div>
            <span className="text-slate-500 uppercase font-bold tracking-wider text-[10px]">{lang === "fr" ? "Période" : "Period"}</span>
            <p className="font-semibold text-sm">{periodLabel}</p>
          </div>
        </div>

        <table className="w-full text-xs border-collapse mb-4">
          <thead>
            <tr className="border-b border-slate-300 text-slate-500 uppercase text-[10px]">
              <th className="text-left py-1.5">{lang === "fr" ? "Date" : "Date"}</th>
              <th className="text-left py-1.5">{lang === "fr" ? "Type" : "Type"}</th>
              <th className="text-left py-1.5">{lang === "fr" ? "Début" : "Start"}</th>
              <th className="text-left py-1.5">{lang === "fr" ? "Fin" : "End"}</th>
              <th className="text-right py-1.5">{lang === "fr" ? "Heures" : "Hours"}</th>
            </tr>
          </thead>
          <tbody>
            {approved.length === 0 ? (
              <tr><td colSpan={5} className="text-center py-4 text-slate-400 italic">{lang === "fr" ? "Aucune entrée approuvée pour cette période." : "No approved entries for this period."}</td></tr>
            ) : approved.map(e => (
              <tr key={e.id} className="border-b border-slate-100">
                <td className="py-1.5 font-mono">{e.date}</td>
                <td className="py-1.5">{TYPE_LABEL[e.type]?.[lang] ?? e.type}</td>
                <td className="py-1.5 font-mono">{e.startTime ?? "—"}</td>
                <td className="py-1.5 font-mono">{e.endTime ?? "—"}</td>
                <td className="py-1.5 text-right font-mono font-semibold">{e.type === "worked" ? `${e.hours.toFixed(2)}h` : "—"}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="flex justify-end gap-8 text-xs border-t border-slate-300 pt-3 mb-6">
          <div className="text-right">
            <span className="text-slate-500 uppercase font-bold tracking-wider text-[10px]">{lang === "fr" ? "Total travaillé" : "Total worked"}</span>
            <p className="font-extrabold text-base">{totalHours.toFixed(2)}h</p>
          </div>
          <div className="text-right">
            <span className="text-slate-500 uppercase font-bold tracking-wider text-[10px]">{lang === "fr" ? "Jours d'absence" : "Absence days"}</span>
            <p className="font-extrabold text-base">{absenceDays}</p>
          </div>
        </div>

        {config.timesheet_signatures && (
          <div className="grid grid-cols-2 gap-8 pt-6 text-xs">
            <div>
              <div className="border-b border-slate-400 h-10" />
              <p className="mt-1 text-slate-500">{lang === "fr" ? "Signature de l'employé — Date :" : "Employee signature — Date:"}</p>
            </div>
            <div>
              <div className="border-b border-slate-400 h-10" />
              <p className="mt-1 text-slate-500">{lang === "fr" ? "Signature du responsable — Date :" : "Manager signature — Date:"}</p>
            </div>
          </div>
        )}

        <p className="text-[9px] text-slate-400 mt-6 italic">
          {lang === "fr"
            ? "Ce document est généré automatiquement à partir des heures approuvées enregistrées dans Brigado et ne constitue pas un avis juridique."
            : "This document is generated automatically from approved hours recorded in Brigado and does not constitute legal advice."}
        </p>
      </div>
    </div>,
    document.body
  );
}
