export type LandingLang = "fr" | "en";

// Marketing/legal copy is kept separate from the in-app translations.ts
// (that file is for the product UI; this is for the public-facing site).
export const landingCopy = {
  fr: {
    heroTitle1: "Heures, plannings et paie du personnel —",
    heroTitle2: "conçu pour les restaurants.",
    heroSub: "Pointage, planning des équipes, suivi des heures supplémentaires et paie précise — le tout accessible depuis le téléphone de votre équipe.",
    featServer: "Pointage en direct",
    featServerSub: "Heures réelles, pas d'approximation — avec détection d'honnêteté intégrée.",
    featRota: "Planning intelligent",
    featRotaSub: "Planning glisser-déposer avec alertes de dépassement horaire.",
    featPayroll: "Chiffres de paie réels",
    featPayrollSub: "Heures, coûts, heures sup. — exportables en un clic.",
    featRequests: "Demandes & messagerie",
    featRequestsSub: "Congés, échanges de service, annonces — fini les groupes WhatsApp.",
    featApproval: "Validation manager",
    featApprovalSub: "Chaque heure saisie est vérifiée avant de compter.",
    featTeam: "Conçu pour les petites équipes",
    featTeamSub: "Pas de superflu — juste ce dont un restaurant a besoin.",
    complianceTitle: "Conçu autour du vrai droit du travail français",
    complianceBody: "Repos quotidien de 11h, plafond hebdomadaire, coupures selon la convention HCR, règles spécifiques aux mineurs — Brigado cite les articles réels du Code du travail, pas des approximations génériques.",
    howTitle: "Comment ça marche",
    howStep1Title: "Inscrivez votre restaurant",
    howStep1Sub: "Ajoutez votre équipe en quelques minutes.",
    howStep2Title: "Imprimez l'affiche QR",
    howStep2Sub: "Un code, collé dans votre restaurant.",
    howStep3Title: "L'équipe pointe depuis son téléphone",
    howStep3Sub: "Aucune installation, aucune app à télécharger.",
    pricingTitle: "Un prix simple, sans surprise",
    pricingSub: "Personnel illimité. Pas de frais cachés.",
    planMonthly: "Mensuel",
    planYearly: "Annuel",
    planSave: "-17%",
    trialNote: "Essai gratuit de 7 jours · carte requise · annulez à tout moment",
    registerTitle: "Inscrivez votre restaurant",
    restaurantName: "Nom du restaurant",
    webAddress: "Votre adresse web",
    checkBtn: "Vérifier",
    available: "✓ Disponible",
    taken: "Déjà pris — essayez-en un autre.",
    invalidSlug: "Entrez au moins 2 caractères.",
    emailLabel: "Votre e-mail (identifiant manager)",
    contactNameLabel: "Nom du contact",
    phoneLabel: "Téléphone",
    postcodeLabel: "Code postal (optionnel)",
    continueToPayment: "Continuer vers le paiement",
    alreadyRegistered: "Déjà inscrit ?",
    goToRestaurant: "Accéder à mon restaurant →",
    faqTitle: "Questions fréquentes",
    faq1Q: "Ça fonctionne sur le téléphone de mon équipe ?",
    faq1A: "Oui — aucune installation. Un code QR affiché au restaurant, et l'équipe pointe directement depuis son navigateur.",
    faq2Q: "Que se passe-t-il à la fin de l'essai gratuit ?",
    faq2A: "Votre carte est débitée automatiquement à la fin des 7 jours, sauf si vous annulez avant. Aucune surprise, aucune action requise si vous continuez.",
    faq3Q: "Puis-je annuler à tout moment ?",
    faq3A: "Oui, à tout moment, directement depuis votre espace de facturation. Aucun engagement de durée.",
    faq4Q: "Mes données et celles de mon équipe sont-elles en sécurité ?",
    faq4A: "Oui — hébergement sécurisé (Firebase/Google Cloud), accès manager protégé par mot de passe, et code PIN individuel pour chaque membre de l'équipe.",
    faq5Q: "Est-ce adapté à mon type d'établissement ?",
    faq5A: "Brigado est conçu pour la restauration et l'hôtellerie — restaurants, bars, cafés, petits hôtels — avec les règles de la convention collective HCR intégrées.",
    faq6Q: "Y a-t-il une limite au nombre d'employés ?",
    faq6A: "Non — le tarif est fixe, quel que soit le nombre de membres dans votre équipe.",
    footerTagline: "Heures, plannings et paie du personnel pour les restaurants.",
    footerLegal: "Légal",
    footerMentions: "Mentions légales",
    footerCGV: "CGV",
    footerPrivacy: "Confidentialité",
    footerContact: "Contact",
    footerRights: "Tous droits réservés.",
  },
  en: {
    heroTitle1: "Staff hours, roster, and payroll —",
    heroTitle2: "built for restaurants.",
    heroSub: "Clock in/out, schedule shifts, track overtime, and pay your team accurately — all in one place your staff can use from their phone.",
    featServer: "Live clock in/out",
    featServerSub: "Real timestamps, not guesswork — with honesty flags built in.",
    featRota: "Smart roster planning",
    featRotaSub: "Drag-and-drop scheduling with overtime warnings.",
    featPayroll: "Real payroll numbers",
    featPayrollSub: "Hours, cost, and overtime — exportable in one click.",
    featRequests: "Requests & messaging",
    featRequestsSub: "Time off, shift cover, and announcements — no more group texts.",
    featApproval: "Manager approval",
    featApprovalSub: "Every hour logged is reviewed before it counts.",
    featTeam: "Built for small teams",
    featTeamSub: "No bloat — just what a restaurant actually needs.",
    complianceTitle: "Built around real French labor law",
    complianceBody: "11-hour daily rest, weekly caps, HCR-agreement split-shift rules, minors' protections — Brigado cites the actual Code du travail articles, not generic approximations.",
    howTitle: "How it works",
    howStep1Title: "Register your restaurant",
    howStep1Sub: "Add your team in a few minutes.",
    howStep2Title: "Print the QR poster",
    howStep2Sub: "One code, posted in your restaurant.",
    howStep3Title: "Your team clocks in from their phone",
    howStep3Sub: "No install, no app to download.",
    pricingTitle: "Simple pricing, no surprises",
    pricingSub: "Unlimited staff. No hidden fees.",
    planMonthly: "Monthly",
    planYearly: "Yearly",
    planSave: "-17%",
    trialNote: "7-day free trial · card required · cancel anytime",
    registerTitle: "Register your restaurant",
    restaurantName: "Restaurant name",
    webAddress: "Your web address",
    checkBtn: "Check",
    available: "✓ Available",
    taken: "Already taken — try another.",
    invalidSlug: "Enter at least 2 characters.",
    emailLabel: "Your email (manager login)",
    contactNameLabel: "Contact name",
    phoneLabel: "Phone",
    postcodeLabel: "Postcode (optional)",
    continueToPayment: "Continue to payment",
    alreadyRegistered: "Already registered?",
    goToRestaurant: "Go to your restaurant →",
    faqTitle: "Frequently asked questions",
    faq1Q: "Does it work on my team's phones?",
    faq1A: "Yes — no installation needed. A QR code posted in your restaurant, and staff clock in straight from their browser.",
    faq2Q: "What happens when the free trial ends?",
    faq2A: "Your card is charged automatically after 7 days unless you cancel first. No surprises, nothing to do if you're continuing.",
    faq3Q: "Can I cancel anytime?",
    faq3A: "Yes, anytime, directly from your billing portal. No minimum commitment.",
    faq4Q: "Is my team's data safe?",
    faq4A: "Yes — secure hosting (Firebase/Google Cloud), password-protected manager access, and an individual PIN for every staff member.",
    faq5Q: "Is this a good fit for my type of business?",
    faq5A: "Brigado is built for restaurants and hospitality — restaurants, bars, cafés, small hotels — with the HCR collective agreement's rules built in.",
    faq6Q: "Is there a limit on how many staff I can add?",
    faq6A: "No — the price is flat, no matter how many people are on your team.",
    footerTagline: "Staff hours, roster, and payroll for restaurants.",
    footerLegal: "Legal",
    footerMentions: "Legal notice",
    footerCGV: "Terms of service",
    footerPrivacy: "Privacy",
    footerContact: "Contact",
    footerRights: "All rights reserved.",
  },
};

export function L(lang: LandingLang, key: keyof typeof landingCopy["fr"]): string {
  return landingCopy[lang][key];
}
